- name: Docker Compose restart
  become: true
  listen: web_app_docker_restart
  community.docker.docker_compose:
    project_src: "{{ web_app_path }}"
    build: true
    restarted: true
    state: present