docker_image_name: 'alyonaart/app-python'
docker_image_version: 'latest'
docker_image: '{{ docker_image_name }}:{{ docker_image_version }}'
internal_port: 8000
external_port: 8000
web_app_name: 'web_app'
web_app_path: /app
web_app_full_wipe: true
