password: ENC[AES256_GCM,data:zEcvil8/,iv:kdpySodfFYE1TDZPJLBQqChMqqcYaae39fIgrZMoZ5E=,tag:BIWp9De4f/AO2nA93E/Whg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-01T12:43:54Z"
    mac: ENC[AES256_GCM,data:E79QUhtwY39OB81MnCTlut268AOuCXCDoBiE4oZVjQV0DCjbESb0RGiACpG0WpOp7OqgzjL+raDpDSNJhT80ty0kMEIV3mO3DlOtl9tDsGvVD8BPwH7e1vR6uaUd2b1COr4veehL8UOKsLsYSSvfHnUCzaepGYhJTF98fCPCl4U=,iv:S+avYZKodY8kofJMC+p0+CPvOZXuqgiCQ88nkcU44Kw=,tag:Imb9yr7oBgbWTDA60FBBOA==,type:str]
    pgp:
        - created_at: "2024-05-01T12:40:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/xhh2j8BYqhAQv/aEWeFhQHrjTcqy3OKRCb+9iqGsUk5fqVEl/Ox/gTs6zd
            Bb/1lu03NLlavdLISqyHMqdBRSdmsgv15+JfojQ3pI8OuST3mhWN7Jad/N3584Kc
            gcaVY853hb738tSsX4llXSmbSV5XclIQ5RSZWUU8FK2xdEMgaHd1zQ7wyA75IrNB
            FvocV8gFOTRB3SiafdQc7KtedWbqhsP5YAy0luxsoGERp41NCyTea2tlPNpKpbm8
            hlBRn51BgqEqV6Trb0JH96QdIuSJDYX0BnLrTR+N004L5/gg6Wx+w36zLF2iiG6H
            9Qk4/jWDiqG1uLdv+BNwQqVh45llev+3banE4TbUDGhZRYqwJ0ipHgy5uwKSQb7L
            W5n3ruKU4vD7GDulTsWPcXoLhj5wR8Phly5BQyfAmOE8/p0j4ISe29uquwZX5zvO
            mpZBqB+ZdquSV/ut/0vjHpwCPpCtzYgwb4aMV2csyKZRh4uwuBbOi1AL13X88dkT
            nhlZxC7XjhMRN1fLMx8e0l4ByKWc/7Z8ake9Gv9deCfq0uttRpejAxNDX80/lMLA
            6yO9Y57A4f+yTWx+jB61+A0euMs+6R8pe5QAsukgqDq8pWzESDyWatPN9m/0aHkm
            gUIBpKisqzVLkfUCPUhp
            =y6ni
            -----END PGP MESSAGE-----
          fp: B4E706E3A6253567CEA6D3474C50FAF9793E70B1
    unencrypted_suffix: _unencrypted
    version: 3.7.3
