password: ENC[AES256_GCM,data:5jAXFhyNSUt+,iv:64ssaTD4Cch60nKY3JOSm32+JVLk9nbiPPGc/Mfuu4Y=,tag:OjHr+Uh9im+ANLdabhTX4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-16T19:32:04Z"
    mac: ENC[AES256_GCM,data:t1Kl9C8V3No59URWl9PpiNaSnu3ryyngWrne1IJxEwSEZT1ib16dBuB+xuCXmBJsMAIJqh1MvuignvyIhsc23wcgYqwrF+QodcIlZ5DhIItGfNOv4Ky5BOZopbY3SwPZWPOaIPS837+cpTD9HikAPvCuzZrXDT7u22J/PiFbwzU=,iv:Zr40uCiArtfzDrbFERF3uWuKNfGXoyynz03id1WRgII=,tag:JAW6DZjqE02jPdwy68JMsA==,type:str]
    pgp:
        - created_at: "2024-04-16T19:30:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA572Ua9pAod8AQv/c7W+bXd3e1bridy64L5s4l9z8WglTT1dxYNtBRto+3Zh
            zXXp+OndWrIQJkLt4CUuQVMSGqUp6ZzTQ0ESOfOYmPUhxa2o2lW6KFYA+hfYIkNn
            5Vvd6baki4VgAsQZEtPkCwL+bj8e5xwKAlFS47glRflBXQycx3Gyzlk7oI1ch+yO
            qIQfnj8B8k5BOxbjJUKZ0dtrXXYVhjscsDsWumaHWMe4AvTvjUzCR9FwT8z5YAXs
            uDXxhow/j4o2TrD9mPNIxRpWUIC36Ga+cpYDQhfwtbnFlXn+Edf+VapHAqddRM8E
            PxdkNDNF8QaT/gn02DWUYPLU/W7U5jN3EoD1Gu4PDSxlO25ZcogDXP1vadt0tuxf
            6vcFfvUug7c0geGZR0SacsyfOkK2N7G1j8v1IkfnlSJsFn3h2/GBD5EcGjG9OzQR
            smAYlBsH9+G2rvqpuMyj882sKW849FiatGlDXIWWC7oZq67gINGoCKR8FrDU7ogi
            FaPr4dLsNfZoEt+gTuEo0l4BJp9oDY76JSQ2TFt4hBDtewGPmhc0iZCX/q5TjhNn
            2jtq4eUqYY8ma+43DSqR2qCGWg2yLQVWrasIsatEy7uShgBxtAX5J6C5u9T/3yHJ
            dQKjHgYrR4ewBKgGXHGy
            =cpYi
            -----END PGP MESSAGE-----
          fp: BE5718E815966713DF9254A2C061BE7BA84A62F4
    unencrypted_suffix: _unencrypted
    version: 3.8.1
