---
- name: Wipe
  block:
  - name: Remove container
    community.docker.docker_compose_v2:
      project_src: "{{ app_dir }}"
      state: absent
      remove_images: all
      remove_volumes: true

  - name: Remove directory
    ansible.builtin.file:
      path: "{{ app_dir }}"
      state: absent