- name: Wipe logic for web app
  block:
    - name: Stop and remove Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        state: absent
  when: web_app_full_wipe | bool
  tags:
    - wipe
