apiVersion: v1
kind: Pod
metadata:
   name: post-install-hook
   annotations:
       "helm.sh/hook": "post-install"
       "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  containers:
  - name: post-install-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo The post-install hook is running && sleep 10' ]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0