apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-python.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "simple-library.labels" . | nindent 6 }}
  endpoints:
  - port: http
