apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: { { include "python-app.fullname" . } }
  labels:
    { { - include "mylibchart.labels" . | nindent 4 } }
spec:
  podManagementPolicy: Parallel
  { { - if not .Values.autoscaling.enabled } }
  replicas: { { .Values.replicaCount } }
  { { - end } }
  selector:
    matchLabels:
      { { - include "mylibchart.labels" . | nindent 6 } }
  template:
    metadata:
      { { - with .Values.podAnnotations } }
      annotations:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      labels:
        { { - include "mylibchart.labels" . | nindent 8 } }
          { { - with .Values.podLabels } }
          { { - toYaml . | nindent 8 } }
          { { - end } }
    spec:
      { { - with .Values.imagePullSecrets } }
      imagePullSecrets:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      serviceAccountName: { { include "python-app.serviceAccountName" . } }
      securityContext:
        { { - toYaml .Values.podSecurityContext | nindent 8 } }
      containers:
        - name: { { .Chart.Name } }
          securityContext:
            { { - toYaml .Values.securityContext | nindent 12 } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          env:
            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password

            - name: CONFIG_MAP_VAR
              valueFrom:
                configMapKeyRef:
                  name: python-app-configmap
                  key: env-var
            { { include "python-app.pythonEnvs" . | nindent 12 } }
            ports:
              - name: http
                containerPort: { { .Values.service.port } }
                protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
          resources:
            { { - toYaml .Values.resources | nindent 12 } }
          { { - with .Values.volumeMounts } }
          volumeMounts:
            { { - toYaml . | nindent 12 } }
          { { - end } }
      { { - with .Values.volumes } }
      volumes:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      { { - with .Values.nodeSelector } }
      nodeSelector:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      { { - with .Values.affinity } }
      affinity:
        { { - toYaml . | nindent 8 } }
      { { - end } }
      { { - with .Values.tolerations } }
      tolerations:
        { { - toYaml . | nindent 8 } }
      { { - end } }
    volumeClaimTemplates:
      - metadata:
          name: { { .Values.vct.name } }
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: { { .Values.vct.storage } }