global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: python-app
    static_configs:
      - targets: ['python-app:5000']

  - job_name: promtail
    static_configs:
      - targets: [ 'promtail:9080' ]

  - job_name: grafana
    static_configs:
      - targets: [ 'grafana:3000' ]