global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: web-app-python
    static_configs:
      - targets: [ 'web-app-python:8080' ]

  - job_name: web-app-java
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'web-app-java:8080' ]

  - job_name: loki
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: promtail
    static_configs:
      - targets: [ 'promtail:9080' ]

  - job_name: grafana
    static_configs:
      - targets: [ 'grafana:3000' ]
