password: ENC[AES256_GCM,data:fLP0VE2PT/cdVw==,iv:E+ZWryMqzd2xHbtDnRRs9PXVILzfN8Z01BG749ZXBuc=,tag:zJrrfbY9u9MoPyrghb+HBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-16T13:46:05Z"
    mac: ENC[AES256_GCM,data:59wL+vWMeCVewvGKDSNQhJmRc571DPtI3s3htWsrEBG+jMWVtyqi+TlW2ntPizt7bAxykeWIzxgfS2AzoBOgoPd1HfGk1JFfo7uBxWuOgMCSuhWEgnOI/Zla1wayYa7HYRZWCTk/8+gC7z2igWCf50lqdoifMJO9ep8HIgzLjcU=,iv:QNJs+8UDYo3rU70WqBIOAtUgRl8Y4veOsAFFPjW/Ioo=,tag:z/DPY2s0NTHzHTHk1HrMjA==,type:str]
    pgp:
        - created_at: "2024-04-16T13:44:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DJFWIfpZVIQoSAQdAvLTYsF2z6RB0x22QJ8rC8JYHc0nOKeaY8DxuPUAPPj8w
            JmPs080cvTz2nJZMTnOX4EXf1ZA+Wb0Sq1PyIvfx2Tf2ZteFrxnWq5svcmiQXeHK
            1GYBCQIQAcScdKFSqttlok/apqyvXyBGUSAwUWdlQ6f63dYrpH2My2cGJfeAFkNW
            PqDiQzSZhGBGFcLHK7Vvv5+W93SapmCCmO553jCpLo+hrCvCin1Rn0HrR1JchEaH
            Wus0q4vxZ4k=
            =I2Nm
            -----END PGP MESSAGE-----
          fp: 8B878F3F418054543516BD01CEB7B3A46DF89265
    unencrypted_suffix: _unencrypted
    version: 3.8.1
