password: ENC[AES256_GCM,data:wI1yEaXqWQnSOg==,iv:Q4xrwBFjRR//45YDvbizQsDn7s81yNMs2xRa3PzMc+I=,tag:NCvPLFF4WuXdR15XzMb7RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-16T09:21:16Z"
    mac: ENC[AES256_GCM,data:cmRz3f4dWllFtbhd88VNkgNfdoTcGltK7PDYgU2pN32zrAGOEHoGcX4RDIll1XeR5GYpkBFiY97RdwwOeMZ5CRVE0o+Ux7o3e0Exc/8KMcgLRXt0TdQbyyE25r2K3qcwfFbkbmyFdPnD+tWap7VjBAyGyawTCkL1ez2TQ7V5ZDA=,iv:k82sdYoTkDUcPT3WuytqkmMLrQZQSQ2Z1N/ojKZkXCs=,tag:q1UcYlzsBaiaSvQjRoXpqw==,type:str]
    pgp:
        - created_at: "2024-04-16T09:21:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----
            hF4D9hi7Af1u3q8SAQdAu/6loLKVUzboZ/73vASqfnLecoZhdu7M2QL+DYks3GUw
            1XQOkIQfXtGXmXNUfSUKvfufTHCnZ3PTcBJsnfLn/4MA00I/EzhU83SMW8sDml0k
            0l4BMyEUTxbr0Z7pr9/Pavug+aco8jUueWv278p5NucXRe/k18svxAzvAnsuStYw
            P+kr030AwEp5K763EL44RYQsSVdG6pvgdMbwSdEPJkvkDwV+I+FPRTHGlhwjHV2r
            =+UT0
            -----END PGP MESSAGE-----
          fp: BF75A36CCDE6020FE073D6BC7B29D59BE5401C07
    unencrypted_suffix: _unencrypted
    version: 3.8.1
