apiVersion: v1
kind: Service
metadata:
  name: app-javascript-service
spec:
  selector:
    app: app-javascript
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer