apiVersion: v1
kind: Service
metadata:
  name: moscow-time-app-service
spec:
  selector:
    app: moscow-time-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
