password: ENC[AES256_GCM,data:lBoApYJ7SkqZcg==,iv:r+Bs7NrqJQLG0mO1VaCFjZ/a9e9i2VhkcA12bsWVFOI=,tag:MYGW7RjLRy76VFGL/zhgSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-13T14:20:45Z"
    mac: ENC[AES256_GCM,data:0IaauZph27G33tCH1YV3AbhkC+XpM5NkgnsVvYFPGLggBKVzvpt/zj4f5GqhDFj6fDf9opc9ZPB/NtkBKnrUIZFfS3aoc4f6F2hNS6xfdeI/UperIKDT9JHfFvFQvSSvjKzmeRxqHzC/1GQ0m0PNmPHKC7/pGK9XuZNNMClecwM=,iv:WjwvwdcNygkwoNnUiLfFZRcWY+1yxbCpTL9Qu483IfI=,tag:fM5fWaeD50Nmf1859tDpRg==,type:str]
    pgp:
        - created_at: "2024-04-13T14:19:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DCUmDteWteNoSAQdAAkXSbX+ytwvaPbxAqcl7k7PK/DLNzOAwFapeVFHRmUsw
            w2C/2uJAvxczidKtv+hYuzlTzuhBTPvf6RLhdYHBnhR87USLNGSMKg2X+fZnxMdY
            1GgBCQIQjoW2ix855o6TWrre5LG1OwzOxeRKbRtIxG2CvGxJiesQptTWFMEdJzQG
            p4ZjqgjMDz/u1qpHMOhjb2zm+2ketXtnkr4Mal+EDpz82uyg3SRC7tLm9p/R+JN0
            nVYm1DhFz9utXw==
            =O4Xo
            -----END PGP MESSAGE-----
          fp: C112BBFF3A45F8E9FCF3523D399EFAA1545B5BD4
    unencrypted_suffix: _unencrypted
    version: 3.8.1