---
- name: Deploy Python Application
  hosts: all
  roles: 
  - role:  ../../../roles/web_app
    become: true
    vars:
      web_app_name: "my-python-app"
      web_app_port: 5000
      web_app_dir: "/home/{{ ansible_user }}/{{ web_app_name }}"
      host_name: "{{ ansible_host }}"
      web_app_full_wipe: true