- name: Install docker
  hosts: all
  roles:
    - role: docker
      become: true

- name: Deploy Python Image
  hosts: all
  roles: 
    - role: web_app
      become: true
      vars:
        app_name: "app_python_image"
        app_port: 5000
        app_dir: "/home/{{ ansible_user }}/{{ app_name }}"
        host_name: "{{ ansible_host }}"
        web_app_full_wipe: true