- hosts: all

  vars:
    pip_install_packages:
      - name: docker
    ansible_ssh_private_key_file: ~/.ssh/id_ed25322

  roles:
#    - geerlingguy.pip
#    - geerlingguy.docker
    - ../../roles/docker

  become: yes

  tasks:
    - name: Install python3-pip package
      apt:
        name: python3-pip
        state: present
