apiVersion: v1
kind: Pod
metadata:
  name: pre-install-hook
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
    - name: pre-install-container
      image: busybox
      args:
        - sleep
        - "20"
  restartPolicy: Never
