apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go-deployment
  labels:
    app: app-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-go
  template:
    metadata:
      labels:
        app: app-go
    spec:
      containers:
      - name: app-go
        image: bulatok4/app_go:latest
        ports:
        - containerPort: 8080