- name: Installation of necessary system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  register: install_packages

- name: Retrieve Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Delete conflicting Docker GPG apt Key
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
  ignore_errors: yes

- name: Add Docker Repository to apt sources
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt cache and install Docker Community Edition (docker-ce)
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  when: install_packages.changed
