---
- name: Install pip
  ansible.builtin.include_tasks:
    file: pip.yml

- name: Install docker
  ansible.builtin.include_tasks:
    file: install_docker.yml

- name: Install docker-compose
  ansible.builtin.include_tasks:
    file: install_compose.yml