- name: Update apt
  apt:
    update_cache: true

- name: Python3 and pip3 installation
  apt:
    name:
      - python3
      - python3-pip

- name: Install docker
  import_tasks: install_docker.yml
  tags: docker

- name: Install docker compose
  import_tasks: install_compose.yml
  tags: docker