---
# Update apt
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

# Uses apt
- name: Install python
  ansible.builtin.apt:
    name:
      - python3
    state: present

# Uses apt
- name: Install pip
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present