name: Python app

on:
  push:
    branches:
      - "feature/**"
    paths:
      - app_python/**

  pull_request:
    branches:
      - "feature/**"
    paths:
      - app_python/**

defaults:
  run:
    working-directory: app_python
    shell: bash

jobs:
  test_app:
    timeout-minutes: 2

    name: Test&lint app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: make init

      - name: Lint check source code
        run: make lint-check

      - name: Testing app
        run: make test

  snyk_check:
    needs: test_app
    timeout-minutes: 3

    name: Run Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        with:
          args: --skip-unresolved app_python/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build_push:
    needs: [test_app, snyk_check]
    timeout-minutes: 3

    name: Docker build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sign in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: app_python
          file: app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab-02-python:latest

          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-lab-02-python:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/devops-lab-02-python:buildcache,mode=max
